# Generated by Django 3.0.6 on 2020-07-27 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200615_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='agility',
            field=models.PositiveIntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='combat',
            field=models.PositiveIntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='constitution',
            field=models.PositiveIntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='defense',
            field=models.PositiveIntegerField(default='10'),
        ),
        migrations.RemoveField(
            model_name='hero',
            name='hero',
        ),
        migrations.AddField(
            model_name='hero',
            name='hero',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hero',
            name='inteligence',
            field=models.PositiveIntegerField(default='10'),
        ),
    ]
