# Generated by Django 3.0.6 on 2020-07-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200727_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='agility',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hero',
            name='combat',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hero',
            name='constitution',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hero',
            name='defense',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hero',
            name='inteligence',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
