# Generated by Django 3.0.6 on 2020-07-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200730_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rod',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
