# Generated by Django 3.0.6 on 2020-08-04 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_fishx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishx',
            name='user',
            field=models.ManyToManyField(related_name='fishesX', to=settings.AUTH_USER_MODEL),
        ),
    ]
