# Generated by Django 3.0.6 on 2020-08-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_fishx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='icon',
        ),
    ]
