# Generated by Django 3.0.6 on 2020-08-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_fish_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='vasu_mointains',
            new_name='vasu_mountains',
        ),
    ]
