# Generated by Django 3.0.6 on 2020-08-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200807_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='dimension_rift',
            new_name='spacetime_rift',
        ),
    ]
