# Generated by Django 3.0.6 on 2020-08-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200807_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='man_eating_swamp',
            new_name='man_eating_marsh',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='rinde_port',
            new_name='rinde',
        ),
    ]
