# Generated by Django 3.0.6 on 2020-08-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200813_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loot', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='fish',
            name='absorb',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fish',
            name='max_points',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='fish',
            name='max_size',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='fish',
            name='min_points',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='fish',
            name='min_size',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='fish',
            name='rarity',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='fish',
            name='resist',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fish',
            name='weak',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fish',
            name='bait',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='fish',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='fish',
            name='hook',
            field=models.CharField(default='Single Catch', max_length=12),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='fish',
            name='reel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fish',
            name='rod',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='fish',
            name='loot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loots', to='users.Loot'),
        ),
        migrations.AddField(
            model_name='fish',
            name='weapon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='users.Weapon'),
        ),
    ]
