# Generated by Django 3.0.6 on 2020-08-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200825_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='weapon',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
