# Generated by Django 3.0.6 on 2020-08-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200825_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='max_size',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='min_size',
            field=models.FloatField(default='0'),
        ),
    ]
