# Generated by Django 3.0.6 on 2020-09-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200929_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters_Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpn_name', models.CharField(blank=True, default='', max_length=30)),
                ('wpn_type', models.CharField(blank=True, default='', max_length=10)),
                ('wpn_atk', models.PositiveIntegerField(default='0')),
                ('wpn_mat', models.PositiveIntegerField(default='0')),
                ('wpn_eb', models.PositiveIntegerField(default='0')),
                ('wpn_nb', models.PositiveIntegerField(default='0')),
                ('wpn_mod1', models.PositiveIntegerField(default='0')),
                ('wpn_mod2', models.PositiveIntegerField(default='0')),
                ('wpn_hp', models.PositiveIntegerField(default='0')),
                ('wpn_mp', models.PositiveIntegerField(default='0')),
                ('wpn_pwr', models.PositiveIntegerField(default='0')),
                ('wpn_int', models.PositiveIntegerField(default='0')),
                ('wpn_end', models.PositiveIntegerField(default='0')),
                ('wpn_spr', models.PositiveIntegerField(default='0')),
                ('wpn_spd', models.PositiveIntegerField(default='0')),
                ('wpn_lck', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='wpn',
            field=models.ManyToManyField(related_name='wpn', to='users.Characters_Weapon'),
        ),
    ]
