# Generated by Django 3.0.6 on 2020-10-03 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200930_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='badge_pwr',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AddField(
            model_name='character',
            name='badge_spd',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='end',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='hp',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='int',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='lck',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='mp',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='pwr',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='spd',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='character_weapon',
            name='spr',
            field=models.IntegerField(default='0'),
        ),
    ]
