# Generated by Django 3.0.6 on 2020-10-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20201004_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='grasta_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta_1', to='users.Character_Grasta'),
        ),
        migrations.AddField(
            model_name='character',
            name='grasta_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta_2', to='users.Character_Grasta'),
        ),
        migrations.AddField(
            model_name='character',
            name='grasta_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta_3', to='users.Character_Grasta'),
        ),
        migrations.AddField(
            model_name='character',
            name='grasta_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta_4', to='users.Character_Grasta'),
        ),
    ]
