# Generated by Django 3.2.6 on 2021-08-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lordofmana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='classe',
            field=models.CharField(default='', help_text='Example: Sorcerer', max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='lezona_floor',
            field=models.CharField(default='', help_text='Example: 2F', max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='location_in_game',
            field=models.CharField(default='', help_text='Example: Tavern', max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='location_rank_up',
            field=models.CharField(default='', help_text='Example: Port Bazaar', max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(default='', help_text='Example: Hungry Professor', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='rank_four',
            field=models.CharField(default='', help_text='Example: N.A.', max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='rank_three',
            field=models.CharField(default='', help_text='Example: 5000', max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='rank_two',
            field=models.CharField(default='', help_text='Example: 1000', max_length=255),
        ),
    ]
