# Generated by Django 3.1.2 on 2021-07-31 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: One Wheel', max_length=30)),
                ('location', models.CharField(help_text='Example: Temple Ruins', max_length=255)),
                ('reward', models.CharField(help_text='Example: Dark Spirit Katana', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bosses',
            },
        ),
        migrations.CreateModel(
            name='Boss_Weakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakness', to='bosses.boss')),
            ],
            options={
                'verbose_name_plural': "Bosses' Weaknesses",
            },
        ),
        migrations.CreateModel(
            name='Boss_Resist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resist', to='bosses.boss')),
            ],
            options={
                'verbose_name_plural': "Bosses' Resistances",
            },
        ),
        migrations.CreateModel(
            name='Boss_Nulify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nulify', to='bosses.boss')),
            ],
            options={
                'verbose_name_plural': "Bosses' Nulifies",
            },
        ),
        migrations.CreateModel(
            name='Boss_Absorb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absorb', to='bosses.boss')),
            ],
            options={
                'verbose_name_plural': "Bosses' Absorbs",
            },
        ),
    ]
