# Generated by Django 3.1.2 on 2021-07-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boss_Absorb',
            new_name='BossAbsorb',
        ),
        migrations.RenameModel(
            old_name='Boss_Nulify',
            new_name='BossNulify',
        ),
        migrations.RenameModel(
            old_name='Boss_Resist',
            new_name='BossResist',
        ),
        migrations.RenameModel(
            old_name='Boss_Weakness',
            new_name='BossWeakness',
        ),
    ]
