# Generated by Django 3.1.2 on 2021-08-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosses', '0003_auto_20210808_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name_plural': 'Bosses'},
        ),
    ]
