# Generated by Django 3.1.2 on 2021-07-31 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Aldo', max_length=30)),
                ('lv', models.PositiveIntegerField(default='1', help_text='Example: 1')),
                ('rarity', models.PositiveIntegerField(default='3', help_text='Example: 3')),
                ('element', models.CharField(help_text='Example: Fire', max_length=10)),
                ('ls_type', models.CharField(help_text='Example: Light', max_length=6)),
                ('ls_count', models.PositiveIntegerField(default='0', help_text='Example: 0')),
                ('another_style', models.BooleanField(default=False, help_text='Example: False')),
                ('attack_type', models.CharField(help_text='Example: Slash', max_length=10)),
                ('weapon_type', models.CharField(help_text='Example: Sword', max_length=10)),
                ('accessory_type', models.CharField(help_text='Example: Bracelet', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
