# Generated by Django 3.1.2 on 2021-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20210802_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.CharField(default='', help_text='Example: Protagonist, Guiding Light, Forager, Sword, Dragon, Baruoki', max_length=255),
        ),
    ]
