# Generated by Django 3.1.2 on 2021-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ls_count',
            field=models.PositiveIntegerField(default='0', help_text='Example: 0'),
        ),
    ]
