# Generated by Django 3.1.2 on 2021-08-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20210802_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
    ]
