# Generated by Django 3.1.2 on 2021-08-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='full_name',
            field=models.CharField(default='', help_text='Example: Aldo', max_length=255),
        ),
    ]
