# Generated by Django 3.1.2 on 2021-08-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20210802_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='number',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.CharField(default='', help_text='URL', max_length=255),
        ),
    ]
