# Generated by Django 3.1.2 on 2021-08-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20210803_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dungeon',
            field=models.CharField(default='', help_text='Example:  Miglance Castle', max_length=255),
        ),
    ]
