# Generated by Django 3.1.2 on 2021-08-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_character_dungeon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='icon',
            field=models.CharField(default='', help_text='Icon URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(default='', help_text='Image URL', max_length=255),
        ),
    ]
