# Generated by Django 3.1.2 on 2021-08-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20210805_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Example: Wisdom Ax', max_length=255)),
                ('category', models.CharField(default='', help_text='Example: Ax', max_length=255)),
                ('icon', models.CharField(default='', help_text='Icon URL', max_length=255)),
                ('atk', models.CharField(default='', help_text='167', max_length=255)),
                ('matk', models.CharField(default='', help_text='133', max_length=255)),
                ('hp_gain', models.CharField(default='0', help_text='0', max_length=255)),
                ('mp_gain', models.CharField(default='0', help_text='0', max_length=255)),
                ('pwr_gain', models.CharField(default='0', help_text='0', max_length=255)),
                ('int_gain', models.CharField(default='0', help_text='0', max_length=255)),
                ('spr_gain', models.CharField(default='0', help_text='30', max_length=255)),
                ('end_gain', models.CharField(default='0', help_text='0', max_length=255)),
                ('spd_gain', models.CharField(default='0', help_text='0', max_length=255)),
                ('spd_loss', models.CharField(default='0', help_text='0', max_length=255)),
                ('lck_gain', models.CharField(default='0', help_text='0', max_length=255)),
                ('elemental_type', models.CharField(default='0', help_text='0', max_length=255)),
                ('non_type', models.CharField(default='0', help_text='0', max_length=255)),
                ('damage_plus', models.CharField(default='0', help_text='0', max_length=255)),
            ],
        ),
    ]
