# Generated by Django 3.0.6 on 2020-06-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='contitution',
            new_name='constitution',
        ),
    ]
