# Generated by Django 3.0.6 on 2020-08-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200804_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FishX',
        ),
    ]
