# Generated by Django 3.0.6 on 2020-09-27 23:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_auto_20200901_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpn_name', models.CharField(blank=True, default='', max_length=30)),
                ('wpn_type', models.CharField(blank=True, default='', max_length=10)),
                ('wpn_atk', models.PositiveIntegerField(default='0')),
                ('wpn_mat', models.PositiveIntegerField(default='0')),
                ('wpn_eb', models.PositiveIntegerField(default='0')),
                ('wpn_nb', models.PositiveIntegerField(default='0')),
                ('wpn_mod1', models.PositiveIntegerField(default='0')),
                ('wpn_mod2', models.PositiveIntegerField(default='0')),
                ('wpn_hp', models.PositiveIntegerField(default='0')),
                ('wpn_mp', models.PositiveIntegerField(default='0')),
                ('wpn_pwr', models.PositiveIntegerField(default='0')),
                ('wpn_int', models.PositiveIntegerField(default='0')),
                ('wpn_end', models.PositiveIntegerField(default='0')),
                ('wpn_spr', models.PositiveIntegerField(default='0')),
                ('wpn_spd', models.PositiveIntegerField(default='0')),
                ('wpn_lck', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('lv', models.PositiveIntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)])),
                ('rarity', models.PositiveIntegerField(default='1')),
                ('element', models.CharField(default='', max_length=10)),
                ('ls_type', models.CharField(default='', max_length=6)),
                ('ls_count', models.PositiveIntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('another_style', models.BooleanField(default=False)),
                ('attack_type', models.CharField(default='', max_length=10)),
                ('weapon_type', models.CharField(default='', max_length=10)),
                ('accessory_type', models.CharField(default='', max_length=10)),
                ('manifest', models.BooleanField(default=False)),
                ('manifest_lvl', models.PositiveIntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hp', models.PositiveIntegerField(default='1')),
                ('hp_l', models.FloatField(default='1')),
                ('mp', models.PositiveIntegerField(default='1')),
                ('mp_l', models.FloatField(default='1')),
                ('pwr', models.PositiveIntegerField(default='1')),
                ('pwr_l', models.FloatField(default='1')),
                ('int', models.PositiveIntegerField(default='1')),
                ('int_l', models.FloatField(default='1')),
                ('end', models.PositiveIntegerField(default='1')),
                ('end_l', models.FloatField(default='1')),
                ('spr', models.PositiveIntegerField(default='1')),
                ('spr_l', models.FloatField(default='1')),
                ('spd', models.PositiveIntegerField(default='1')),
                ('spd_l', models.FloatField(default='1')),
                ('lck', models.PositiveIntegerField(default='1')),
                ('lck_l', models.FloatField(default='1')),
                ('gn_1', models.CharField(blank=True, default='', max_length=5)),
                ('gl_1', models.PositiveIntegerField(default='0')),
                ('gn_2', models.CharField(blank=True, default='', max_length=5)),
                ('gl_2', models.PositiveIntegerField(default='0')),
                ('gn_3', models.CharField(blank=True, default='', max_length=5)),
                ('gl_3', models.PositiveIntegerField(default='0')),
                ('gn_4', models.CharField(blank=True, default='', max_length=5)),
                ('gl_4', models.PositiveIntegerField(default='0')),
                ('gn_5', models.CharField(blank=True, default='', max_length=5)),
                ('gl_5', models.PositiveIntegerField(default='0')),
                ('gn_6', models.CharField(blank=True, default='', max_length=5)),
                ('gl_6', models.PositiveIntegerField(default='0')),
                ('gn_7', models.CharField(blank=True, default='', max_length=5)),
                ('gl_7', models.PositiveIntegerField(default='0')),
                ('gn_8', models.CharField(blank=True, default='', max_length=5)),
                ('gl_8', models.PositiveIntegerField(default='0')),
                ('gn_9', models.CharField(blank=True, default='', max_length=5)),
                ('gl_9', models.PositiveIntegerField(default='0')),
                ('gn_10', models.CharField(blank=True, default='', max_length=5)),
                ('gl_10', models.PositiveIntegerField(default='0')),
                ('character_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='users.Character_Weapon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
