# Generated by Django 3.0.6 on 2020-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200927_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dgn_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
