# Generated by Django 3.0.6 on 2020-09-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200929_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_weapon',
            name='weapon',
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='users.Character_Weapon'),
        ),
    ]
