# Generated by Django 3.0.6 on 2020-09-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200929_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.DeleteModel(
            name='Character_Weapon',
        ),
    ]
