# Generated by Django 3.0.6 on 2020-10-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200929_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('type', models.CharField(blank=True, default='', max_length=10)),
                ('atk', models.PositiveIntegerField(default='0')),
                ('mat', models.PositiveIntegerField(default='0')),
                ('eb', models.PositiveIntegerField(default='0')),
                ('nb', models.PositiveIntegerField(default='0')),
                ('mod1', models.PositiveIntegerField(default='0')),
                ('mod2', models.PositiveIntegerField(default='0')),
                ('hp', models.PositiveIntegerField(default='0')),
                ('mp', models.PositiveIntegerField(default='0')),
                ('pwr', models.PositiveIntegerField(default='0')),
                ('int', models.PositiveIntegerField(default='0')),
                ('end', models.PositiveIntegerField(default='0')),
                ('spr', models.PositiveIntegerField(default='0')),
                ('spd', models.PositiveIntegerField(default='0')),
                ('lck', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='wpn',
        ),
        migrations.DeleteModel(
            name='Characters_Weapon',
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='users.Character_Weapon'),
            preserve_default=False,
        ),
    ]
