# Generated by Django 3.0.6 on 2020-10-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20201004_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='grasta1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta1', to='users.Character_Grasta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='grasta2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta2', to='users.Character_Grasta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='grasta3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta3', to='users.Character_Grasta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='grasta4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grasta4', to='users.Character_Grasta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character_grasta',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
