# Generated by Django 3.0.6 on 2020-10-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201004_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='grasta1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='grasta2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='grasta3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='grasta4',
        ),
    ]
