# Generated by Django 3.0.6 on 2020-10-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201004_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('element', models.CharField(default='', max_length=10)),
                ('type', models.CharField(default='', max_length=10)),
                ('multiplier', models.PositiveIntegerField(default='0')),
                ('hits', models.PositiveIntegerField(default='0')),
                ('stacks', models.PositiveIntegerField(default='0')),
            ],
        ),
    ]
