# Generated by Django 3.1.2 on 2021-07-30 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0037_auto_20201006_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: One Wheel', max_length=30)),
                ('location', models.CharField(help_text='Example: Temple Ruins', max_length=255)),
                ('reward', models.CharField(help_text='Example: Dark Spirit Katana', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boss_Weakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses_weakness', to='users.boss')),
            ],
        ),
        migrations.CreateModel(
            name='Boss_Resist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('resist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses_resist', to='users.boss')),
            ],
        ),
        migrations.CreateModel(
            name='Boss_Nulify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('nulify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses_nulify', to='users.boss')),
            ],
        ),
        migrations.CreateModel(
            name='Boss_Absorb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=10)),
                ('absorb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses_absorb', to='users.boss')),
            ],
        ),
    ]
