# Generated by Django 3.1.2 on 2021-07-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_boss_boss_absorb_boss_nulify_boss_resist_boss_weakness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss_absorb',
            name='absorb',
        ),
        migrations.RemoveField(
            model_name='boss_nulify',
            name='nulify',
        ),
        migrations.RemoveField(
            model_name='boss_resist',
            name='resist',
        ),
        migrations.RemoveField(
            model_name='boss_weakness',
            name='weakness',
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name_plural': 'Fishes'},
        ),
        migrations.DeleteModel(
            name='Boss',
        ),
        migrations.DeleteModel(
            name='Boss_Absorb',
        ),
        migrations.DeleteModel(
            name='Boss_Nulify',
        ),
        migrations.DeleteModel(
            name='Boss_Resist',
        ),
        migrations.DeleteModel(
            name='Boss_Weakness',
        ),
    ]
