# Generated by Django 3.2.6 on 2021-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Example: Peasuke', max_length=255, unique=True)),
                ('icon', models.CharField(default='', help_text='URL', max_length=255)),
                ('location', models.CharField(default='', help_text='Example: Baruoki - South', max_length=255)),
                ('liked_gifs', models.CharField(default='', help_text='Decent Small Fish, Cute Butterfly', max_length=255)),
                ('loved_gifs', models.CharField(default='', help_text='Yummy Small Fish, Winged Fish', max_length=255)),
                ('personality', models.CharField(default='', help_text='Docile', max_length=255)),
                ('common_gift', models.CharField(default='', help_text='Catgrass', max_length=255)),
                ('common_icon', models.CharField(default='', help_text='URL', max_length=255)),
                ('unique_gift', models.CharField(default='', help_text='Cats-eye', max_length=255)),
                ('unique_icon', models.CharField(default='', help_text='URL', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
