# Generated by Django 3.2.6 on 2021-08-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='liked_gifs',
            new_name='liked_gifts',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='loved_gifs',
            new_name='loved_gifts',
        ),
    ]
