# Generated by Django 3.1.2 on 2021-07-31 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loot', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default='0')),
                ('description', models.CharField(blank=True, default='', max_length=1)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('hook', models.CharField(default='Single Catch', max_length=12)),
                ('actual_catch', models.PositiveIntegerField(default='0')),
                ('stones', models.PositiveIntegerField(default='0')),
                ('c_stones', models.PositiveIntegerField(default='0')),
                ('rod', models.PositiveIntegerField(blank=True, default='0')),
                ('bait', models.CharField(blank=True, default='', max_length=30)),
                ('reel', models.CharField(blank=True, default='', max_length=20)),
                ('xp', models.PositiveIntegerField(default='0')),
                ('rarity', models.PositiveIntegerField(default='1')),
                ('min_size', models.FloatField(default='0')),
                ('max_size', models.FloatField(default='0')),
                ('min_points', models.FloatField(default='0')),
                ('max_points', models.FloatField(default='0')),
                ('weak', models.CharField(blank=True, default='none', max_length=10)),
                ('resist', models.CharField(blank=True, default='none', max_length=10)),
                ('absorb', models.CharField(blank=True, default='none', max_length=10)),
                ('lake_tiilen', models.BooleanField(default=False)),
                ('dragon_palace', models.BooleanField(default=False)),
                ('acteul', models.BooleanField(default=False)),
                ('vasu_mountains', models.BooleanField(default=False)),
                ('charol_plains', models.BooleanField(default=False)),
                ('man_eating_marsh', models.BooleanField(default=False)),
                ('baruoki', models.BooleanField(default=False)),
                ('nauru_uplands', models.BooleanField(default=False)),
                ('karek_swampland', models.BooleanField(default=False)),
                ('rinde', models.BooleanField(default=False)),
                ('serena_coast', models.BooleanField(default=False)),
                ('rucyana_sands', models.BooleanField(default=False)),
                ('elzion_airport', models.BooleanField(default=False)),
                ('nilva', models.BooleanField(default=False)),
                ('last_island', models.BooleanField(default=False)),
                ('spacetime_rift', models.BooleanField(default=False)),
                ('zol_plains', models.BooleanField(default=False)),
                ('moonlight_forest', models.BooleanField(default=False)),
                ('snake_neck_igoma', models.BooleanField(default=False)),
                ('ancient_battlefield', models.BooleanField(default=False)),
                ('loot', models.ManyToManyField(blank=True, default=None, related_name='loots', to='fishing.Loot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishes', to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ManyToManyField(blank=True, default=None, related_name='weapons', to='fishing.Weapon')),
            ],
            options={
                'verbose_name_plural': 'Fishes',
            },
        ),
    ]
